import type { TrendingToken } from "@/components/trending-token-card"

export const tokens: TrendingToken[] = [
  {
    name: "MoonCoin",
    symbol: "MOON",
    chain: "Base",
    description: "The first community-driven meme coin for space enthusiasts",
    progress: 78,
    raised: "12.5 ETH",
    goal: "16 ETH",
    backers: 234,
    daysLeft: 3,
  },
  {
    name: "DeFiPro",
    symbol: "DPRO",
    chain: "Solana",
    description: "Professional-grade DeFi tools for everyone",
    progress: 45,
    raised: "18.2 SOL",
    goal: "40 SOL",
    backers: 156,
    daysLeft: 8,
  },
  {
    name: "GameFi Plus",
    symbol: "GFP",
    chain: "Base",
    description: "Next-gen gaming platform with Play-to-Earn mechanics",
    progress: 92,
    raised: "23.1 ETH",
    goal: "25 ETH",
    backers: 589,
    daysLeft: 1,
  },
  {
    name: "AI Assist",
    symbol: "AIA",
    chain: "Avalanche",
    description: "AI-powered crypto trading assistant",
    progress: 60,
    raised: "9.0 AVAX",
    goal: "15 AVAX",
    backers: 112,
    daysLeft: 5,
  },
  {
    name: "EcoToken",
    symbol: "ECO",
    chain: "Solana",
    description: "Token supporting global sustainability projects",
    progress: 30,
    raised: "6.5 SOL",
    goal: "20 SOL",
    backers: 64,
    daysLeft: 12,
  },
  {
    name: "MetaVerseHub",
    symbol: "MVH",
    chain: "Base",
    description: "Gateway to multiple metaverse worlds",
    progress: 80,
    raised: "20 ETH",
    goal: "25 ETH",
    backers: 340,
    daysLeft: 2,
  },
]
