import type { TrendingToken } from "@/components/trending-token-card"

export const tokens: TrendingToken[] = [
  {
    name: "MoonCoin",
    symbol: "MOON",
    chain: "Base",
    description: "The first community-driven meme coin for space enthusiasts",
    progress: 78,
    raised: "12.5 ETH",
    goal: "16 ETH",
    backers: 234,
    daysLeft: 3,
    website: "https://mooncoin.example",
    launchDate: "2024-08-01",
    launchPrice: "0.01 ETH",
    totalSupply: "1B",
  },
  {
    name: "DeFiPro",
    symbol: "DPRO",
    chain: "Solana",
    description: "Professional-grade DeFi tools for everyone",
    progress: 45,
    raised: "18.2 SOL",
    goal: "40 SOL",
    backers: 156,
    daysLeft: 8,
    website: "https://defipro.example",
    launchDate: "2024-08-15",
    launchPrice: "0.5 SOL",
    totalSupply: "500M",
  },
  {
    name: "GameFi Plus",
    symbol: "GFP",
    chain: "Base",
    description: "Next-gen gaming platform with Play-to-Earn mechanics",
    progress: 92,
    raised: "23.1 ETH",
    goal: "25 ETH",
    backers: 589,
    daysLeft: 1,
    website: "https://gamefiplus.example",
    launchDate: "2024-08-20",
    launchPrice: "0.02 ETH",
    totalSupply: "2B",
  },
  {
    name: "AI Assist",
    symbol: "AIA",
    chain: "Avalanche",
    description: "AI-powered crypto trading assistant",
    progress: 60,
    raised: "9.0 AVAX",
    goal: "15 AVAX",
    backers: 112,
    daysLeft: 5,
    website: "https://aiassist.example",
    launchDate: "2024-08-10",
    launchPrice: "1 AVAX",
    totalSupply: "100M",
  },
  {
    name: "EcoToken",
    symbol: "ECO",
    chain: "Solana",
    description: "Token supporting global sustainability projects",
    progress: 30,
    raised: "6.5 SOL",
    goal: "20 SOL",
    backers: 64,
    daysLeft: 12,
    website: "https://ecotoken.example",
    launchDate: "2024-09-01",
    launchPrice: "0.2 SOL",
    totalSupply: "300M",
  },
  {
    name: "MetaVerseHub",
    symbol: "MVH",
    chain: "Base",
    description: "Gateway to multiple metaverse worlds",
    progress: 80,
    raised: "20 ETH",
    goal: "25 ETH",
    backers: 340,
    daysLeft: 2,
    website: "https://metaversehub.example",
    launchDate: "2024-08-05",
    launchPrice: "0.015 ETH",
    totalSupply: "750M",
  },
]
